name: "Automate GitHub Wiki page maintenance"
description: "Add tables of contents to Markdown wiki pages."
author: Justin Forest <hex@umonkey.net>

branding:
  icon: "file-text"
  color: "green"

inputs:
  path:
    description: "The folder where the wiki repository files are."
    required: true
  update_tocs:
    description: "Update existing tables of contents."
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - name: "Update tables of contents"
      run: |
        python3 $ACTION_PATH/bin/update-tocs $INPUT_PATH/*.md
      shell: bash
      env:
        INPUT_PATH: ${{ inputs.path }}
        ACTION_PATH: ${{ github.action_path }}
