name: "Automate GitHub Wiki page maintenance"
description: "Add tables of contents to Markdown wiki pages."
author: Justin Forest <hex@umonkey.net>

branding:
  icon: "file-text"
  color: "green"

inputs:
  path:
    description: "The folder where the wiki repository files are."
    required: true
  update_tocs:
    description: "Update existing tables of contents."
    required: false
    default: true
  update_backlinks:
    description: "Update existing backlinks."
    required: false
    default: true
  backlinks_header:
    description: "Override the default backlinks header."
    required: false
    default: "## Pages that link here"
  toc_header:
    description: "Override the default table of contents header."
    required: false
    default: "**Table of Contents:**"

runs:
  using: "composite"
  steps:
    - name: "Update backlinks"
      run: |
        python3 $ACTION_PATH/bin/update-backlinks $INPUT_PATH/*.md
      shell: bash
      env:
        INPUT_PATH: ${{ inputs.path }}
        ACTION_PATH: ${{ github.action_path }}
        WIKI_BACKLINKS_HEADER: ${{ inputs.backlinks_header }}

    - name: "Update tables of contents"
      run: |
        python3 $ACTION_PATH/bin/update-tocs $INPUT_PATH/*.md
      shell: bash
      env:
        INPUT_PATH: ${{ inputs.path }}
        ACTION_PATH: ${{ github.action_path }}
        WIKI_TOC_HEADER: ${{ inputs.toc_header }}
